### ISSUE TITLE
MzTabExporter output, headers and columns mismatch in PEP section

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1801]
Headers and columns in this [1] MzTabExporter output are incorrect. Reported by @ypriverol. 

[1] https://gist.github.com/lars20070/a93cfa75e48df54f5843

**Comment by jpfeuffer** [comment]
How incorrect? I mean, which ones exactly?

**Comment by ypriverol** [comment]
@jpfeuffer some small details:
  1- In the peptide section PEH you can't put peptides without sequences as NULL, as far as I know all 
      evidences should be should contains peptide sequences.
  2- The second issue is related with Modifications, I exported from a consensusXML to mzTab and the 
       exporter put the modifications under a search engine column.

**Comment by jpfeuffer** [comment]
Ah I see, so 1- is related to issue #1800 
and 2- is a problem because e.g. 3-UniMod:4 occurs in the 10th column of PEP which is search_engine_score[1]_ms_run[2] ?

**Comment by ypriverol** [comment]
Yes.

**Comment by timosachsenberg** [comment]
Hi @ypriverol the column is mandatory but the sequence may be null. Otherwise you could not report features without assigned peptide identficiation.

**Comment by ypriverol** [comment]
@timo have you check that?

**Comment by lars20070** [comment]
@timosachsenberg #1800 is about the missing sequences.
This issue is about a mismatch of headers and columns.

**Comment by timosachsenberg** [comment]
ok sorry - this was not clear to me from the title and content of this issue.

**Comment by timosachsenberg** [comment]
can you provide the consensusXML (ideally with only a few elements)?

**Comment by VOOginga** [comment]
I also face the same problem Timo. The columns in the MzTabExporter output do not match and some columns in the end are empty despite having column headings. I have attached a consensus file ( a small RT slice) to help figure out the problem. Cheers

https://gist.github.com/VOOginga/4e3716f4a21cddbabd90

**Comment by timosachsenberg** [comment]
https://github.com/OpenMS/OpenMS/pull/1810 should fix the number of columns.

**Comment by VOOginga** [comment]
Hallo Timo
Thanks for updating the code on the MZTab Exporter but we still have a problem. The columns still do not match and some of them lack headers. Kindly have a look at this

https://gist.github.com/VOOginga/632a9702389fa22bd405

**Comment by timosachsenberg** [comment]
Hi, can you provide me the consensusXML?

**Comment by VOOginga** [comment]
Its the same consensus xml i posted on Gits yesterday
Thread #1801
Check it out

**Comment by timosachsenberg** [comment]
hi. can you recreate the consensusXML using the current (development) version? there have been some changes how the ms run is saved in the file. Maybe the issue is already resolved if the updated MzTabExporter is used with the new file.

**Comment by VOOginga** [comment]
Cool...I will run it on monday n inform u. Thanks

**Comment by VOOginga** [comment]
After the new full run, I would like to say that the MzTab Exporter worked. All the columns match as expected. Thanks Timo

**Comment by ypriverol** [comment]
@timosachsenberg @lars20070  I will check the current output with our readers here. I'm fixing a couple of bugs in our side (jmztab reader). I can close the issue by the end of the day if everything goes well.

**Comment by timosachsenberg** [comment]
sound great

**Comment by timosachsenberg** [comment]
Any update?

**Comment by lars20070** [comment]
Still mods in RT column [2]. Fresh 'consensusXML' from 'FeatureFinderLabeled' [1].

[1] https://gist.github.com/lars20070/4e9c760fe88e224d0ad0
[2] https://gist.github.com/lars20070/2bee601aa6d5555d8fae
