### ISSUE TITLE
IDMerger or ID engine: non-unique identifiers created [199]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#199]
Submitted by timosachsenberg on 2010-10-07 12:48:40

Merging a large number of idXML files bails out with:

Error: The identifier 'OMSSA_2010-08-25T17:01:00' was used before!

Possible reason: Running a ID engine with small databases or multiple threads produces protein identifications with the same identifier (time-stamp doesn't change between two consecutive runs)

---

Commented by cbielow on 2010-10-12 19:09:30:
this is also a problem when importing from e.g. pepXML files, which might have been created in parallel as well.

We could resort to uniqueID's as done for featureXML, but we'd need to store it in the idXML file - currently there is no tag for that but we could add it.

---

Commented by hendrikweisser on 2010-10-15 04:16:31:
Fixed in rev. 7475: If a conflicting ID is found, the date/time of the respective run is increased in steps of seconds until the ID is unique.

However, this is an ugly work-around. I agree with Chris that we should really use unique IDs and store them in the idXML (if we keep using idXML).

---

Commented by cbielow on 2010-10-18 00:06:27:
*\* reopened as solution is not ideal (e.g. we loose tracing right now) and we need to keep an eye on this

---

Commented by hendrikweisser on 2011-02-17 17:13:10:
Related to ticket #70.

**Comment by hroest** [comment]
this was apparently partial fixed in 30202cc5012515980ae328f2ed80611fef526af0

**Comment by mwalzer** [comment]
comment from developer retreat 2016 - 
this should be completely fixed with migration to mzid. 
Push to complete migration.

**Comment by timosachsenberg** [comment]
state here? I think its not fixed (and don't recall why mzid helps here).
