### ISSUE TITLE
pyopenms build issues on ubuntu 16.04

### ISSUE THREAD

**Issue by malmstroem** [OpenMS/OpenMS#2021]
Hi,

I'm trying to build pyopenms, but this fails with:

```
INFO:root:parse /usr/local/openms/OpenMS/src/pyOpenMS/pxds/InternalCalibration.pxd

Error compiling Cython file:
------------------------------------------------------------
...
        #    ProgressLogger

        InternalCalibration()      nogil except +
        InternalCalibration(InternalCalibration) nogil except +

        Size fillCalibrants(MSExperiment[Peak1D,ChromatogramPeak], libcpp_vector[InternalCalibration::LockMass], double tol_ppm, bool, bool, bool) nogil except +
                                                                                                   ^
------------------------------------------------------------

/usr/local/openms/OpenMS/src/pyOpenMS/pxds/InternalCalibration.pxd:20:100: Expected ']', found ':'

Error compiling Cython file:
------------------------------------------------------------
...
        #    ProgressLogger

        InternalCalibration()      nogil except +
        InternalCalibration(InternalCalibration) nogil except +

        Size fillCalibrants(MSExperiment[Peak1D,ChromatogramPeak], libcpp_vector[InternalCalibration::LockMass], double tol_ppm, bool, bool, bool) nogil except +
                                                                                                   ^
------------------------------------------------------------

/usr/local/openms/OpenMS/src/pyOpenMS/pxds/InternalCalibration.pxd:20:100: Expected ']', found ':'
Traceback (most recent call last):
  File "create_cpp_extension.py", line 44, in <module>
    decls, instance_map = autowrap.parse(pxd_files, ".")
  File "/usr/local/lib/python2.7/dist-packages/autowrap/__init__.py", line 51, in parse
    return DeclResolver.resolve_decls_from_files(files, root)
  File "/usr/local/lib/python2.7/dist-packages/autowrap/DeclResolver.py", line 172, in resolve_decls_from_files
    decls.extend(PXDParser.parse_pxd_file(full_path))
  File "/usr/local/lib/python2.7/dist-packages/autowrap/PXDParser.py", line 421, in parse_pxd_file
    root = pipeline[0](source)  # only parser
  File "/usr/local/lib/python2.7/dist-packages/Cython/Compiler/Pipeline.py", line 35, in parse
    tree = context.parse(source_desc, scope, pxd = 0, full_module_name = full_module_name)
  File "/usr/local/lib/python2.7/dist-packages/Cython/Compiler/Main.py", line 354, in parse
    tree = Parsing.p_module(s, pxd, full_module_name)
  File "Cython/Compiler/Parsing.py", line 3530, in Cython.Compiler.Parsing.p_module (/tmp/pip-build-PaDScZ/cython/Cython/Compiler/Parsing.c:60088)
  File "Cython/Compiler/Parsing.py", line 3545, in Cython.Compiler.Parsing.p_module (/tmp/pip-build-PaDScZ/cython/Cython/Compiler/Parsing.c:59817)
  File "Cython/Compiler/Parsing.py", line 2249, in Cython.Compiler.Parsing.p_statement_list (/tmp/pip-build-PaDScZ/cython/Cython/Compiler/Parsing.c:38898)
  File "Cython/Compiler/Parsing.py", line 2181, in Cython.Compiler.Parsing.p_statement (/tmp/pip-build-PaDScZ/cython/Cython/Compiler/Parsing.c:37739)
  File "Cython/Compiler/Parsing.py", line 2952, in Cython.Compiler.Parsing.p_cdef_statement (/tmp/pip-build-PaDScZ/cython/Cython/Compiler/Parsing.c:49524)
  File "Cython/Compiler/Parsing.py", line 3003, in Cython.Compiler.Parsing.p_cdef_extern_block (/tmp/pip-build-PaDScZ/cython/Cython/Compiler/Parsing.c:50565)
  File "Cython/Compiler/Parsing.py", line 2263, in Cython.Compiler.Parsing.p_suite (/tmp/pip-build-PaDScZ/cython/Cython/Compiler/Parsing.c:39134)
  File "Cython/Compiler/Parsing.py", line 2274, in Cython.Compiler.Parsing.p_suite_with_docstring (/tmp/pip-build-PaDScZ/cython/Cython/Compiler/Parsing.c:39283)
  File "Cython/Compiler/Parsing.py", line 2249, in Cython.Compiler.Parsing.p_statement_list (/tmp/pip-build-PaDScZ/cython/Cython/Compiler/Parsing.c:38898)
  File "Cython/Compiler/Parsing.py", line 2181, in Cython.Compiler.Parsing.p_statement (/tmp/pip-build-PaDScZ/cython/Cython/Compiler/Parsing.c:37739)
  File "Cython/Compiler/Parsing.py", line 2972, in Cython.Compiler.Parsing.p_cdef_statement (/tmp/pip-build-PaDScZ/cython/Cython/Compiler/Parsing.c:49965)
  File "Cython/Compiler/Parsing.py", line 3605, in Cython.Compiler.Parsing.p_cpp_class_definition (/tmp/pip-build-PaDScZ/cython/Cython/Compiler/Parsing.c:60992)
  File "Cython/Compiler/Parsing.py", line 3629, in Cython.Compiler.Parsing.p_cpp_class_attribute (/tmp/pip-build-PaDScZ/cython/Cython/Compiler/Parsing.c:61329)
  File "Cython/Compiler/Parsing.py", line 3161, in Cython.Compiler.Parsing.p_c_func_or_var_declaration (/tmp/pip-build-PaDScZ/cython/Cython/Compiler/Parsing.c:52944)
  File "Cython/Compiler/Parsing.py", line 2674, in Cython.Compiler.Parsing.p_c_declarator (/tmp/pip-build-PaDScZ/cython/Cython/Compiler/Parsing.c:45653)
  File "Cython/Compiler/Parsing.py", line 2705, in Cython.Compiler.Parsing.p_c_declarator (/tmp/pip-build-PaDScZ/cython/Cython/Compiler/Parsing.c:45438)
  File "Cython/Compiler/Parsing.py", line 2721, in Cython.Compiler.Parsing.p_c_func_declarator (/tmp/pip-build-PaDScZ/cython/Cython/Compiler/Parsing.c:45869)
  File "Cython/Compiler/Parsing.py", line 2866, in Cython.Compiler.Parsing.p_c_arg_list (/tmp/pip-build-PaDScZ/cython/Cython/Compiler/Parsing.c:48350)
  File "Cython/Compiler/Parsing.py", line 2873, in Cython.Compiler.Parsing.p_c_arg_list (/tmp/pip-build-PaDScZ/cython/Cython/Compiler/Parsing.c:48106)
  File "Cython/Compiler/Parsing.py", line 2903, in Cython.Compiler.Parsing.p_c_arg_decl (/tmp/pip-build-PaDScZ/cython/Cython/Compiler/Parsing.c:48643)
  File "Cython/Compiler/Parsing.py", line 2351, in Cython.Compiler.Parsing.p_c_base_type (/tmp/pip-build-PaDScZ/cython/Cython/Compiler/Parsing.c:40409)
  File "Cython/Compiler/Parsing.py", line 2464, in Cython.Compiler.Parsing.p_c_simple_base_type (/tmp/pip-build-PaDScZ/cython/Cython/Compiler/Parsing.c:42242)
  File "Cython/Compiler/Parsing.py", line 2482, in Cython.Compiler.Parsing.p_buffer_or_template (/tmp/pip-build-PaDScZ/cython/Cython/Compiler/Parsing.c:42505)
  File "Cython/Compiler/Scanning.py", line 481, in Cython.Compiler.Scanning.PyrexScanner.expect (/tmp/pip-build-PaDScZ/cython/Cython/Compiler/Scanning.c:10813)
  File "Cython/Compiler/Scanning.py", line 497, in Cython.Compiler.Scanning.PyrexScanner.expected (/tmp/pip-build-PaDScZ/cython/Cython/Compiler/Scanning.c:11101)
  File "Cython/Compiler/Scanning.py", line 475, in Cython.Compiler.Scanning.PyrexScanner.error (/tmp/pip-build-PaDScZ/cython/Cython/Compiler/Scanning.c:10719)
Cython.Compiler.Errors.CompileError:
Error compiling Cython file:
------------------------------------------------------------
...
        #    ProgressLogger

        InternalCalibration()      nogil except +
        InternalCalibration(InternalCalibration) nogil except +

        Size fillCalibrants(MSExperiment[Peak1D,ChromatogramPeak], libcpp_vector[InternalCalibration::LockMass], double tol_ppm, bool, bool, bool) nogil except +
                                                                                                   ^
------------------------------------------------------------

/usr/local/openms/OpenMS/src/pyOpenMS/pxds/InternalCalibration.pxd:20:100: Expected ']', found ':'
src/pyOpenMS/CMakeFiles/pyopenms_create_cpp.dir/build.make:58: recipe for target 'src/pyOpenMS/CMakeFiles/pyopenms_create_cpp' failed
make[3]: *** [src/pyOpenMS/CMakeFiles/pyopenms_create_cpp] Error 1
CMakeFiles/Makefile2:1258: recipe for target 'src/pyOpenMS/CMakeFiles/pyopenms_create_cpp.dir/all' failed
make[2]: *** [src/pyOpenMS/CMakeFiles/pyopenms_create_cpp.dir/all] Error 2
CMakeFiles/Makefile2:1298: recipe for target 'src/pyOpenMS/CMakeFiles/pyopenms.dir/rule' failed
make[1]: *** [src/pyOpenMS/CMakeFiles/pyopenms.dir/rule] Error 2
Makefile:602: recipe for target 'pyopenms' failed
make: *** [pyopenms] Error 2
```

Any suggestions would be greatly appreciated.

Best regards,
Lars

**Comment by hroest** [comment]
this may be a general issue regarding pyOpenMS as the nightlies are also down, it should be fixed with #2033 - can you try the current develop branch?

**Comment by malmstroem** [comment]
Hi Hannes,

Thanks a lot for looking into this! Closer, but I still have a small issue:

git show-branch
[develop] Merge pull request #2034 from hroest/fix/typos

I can build OpenMS and run cmake -DPYOPENMS=ON .

----
-- Building OpenMS 2.0.1
--   - Repository revision c23217e
--   - Repository branch develop
--   - Repository last change date 2016-07-06 10:34:36 -0700
...
...
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/openms/OpenMS
---

make pyopenms runs for a while, but fails with:
---
...
...
INFO:root:   create wrapper for updateRanges ('void updateRanges()')
INFO:root:   create wrapper for push_back ('void push_back(PeakT)')
Traceback (most recent call last):
  File "create_cpp_extension.py", line 66, in <module>
    extra_opts=None, include_boost=False)
  File "/usr/local/lib/python2.7/dist-packages/autowrap/Main.py", line 190,
in create_wrapper_code
    inc_dirs = autowrap.generate_code(decls, instance_map, out, False,
manual_code, cimports, include_boost)
  File "/usr/local/lib/python2.7/dist-packages/autowrap/__init__.py", line
63, in generate_code
    gen.create_pyx_file(debug)
  File "/usr/local/lib/python2.7/dist-packages/autowrap/CodeGenerator.py",
line 170, in create_pyx_file
    create_for(ResolvedClass, self.create_wrapper_for_class)
  File "/usr/local/lib/python2.7/dist-packages/autowrap/CodeGenerator.py",
line 166, in create_for
    method(resolved)
  File "/usr/local/lib/python2.7/dist-packages/autowrap/CodeGenerator.py",
line 299, in create_wrapper_for_class
    codes = self.create_wrapper_for_method(r_class, name, methods)
  File "/usr/local/lib/python2.7/dist-packages/autowrap/CodeGenerator.py",
line 411, in create_wrapper_for_method
    code = self.create_wrapper_for_nonoverloaded_method(cdcl, py_name,
methods[0])
  File "/usr/local/lib/python2.7/dist-packages/autowrap/CodeGenerator.py",
line 553, in create_wrapper_for_nonoverloaded_method
    method)
  File "/usr/local/lib/python2.7/dist-packages/autowrap/CodeGenerator.py",
line 453, in _create_fun_decl_and_input_conversion
    converter = self.cr.get(t)
  File
"/usr/local/lib/python2.7/dist-packages/autowrap/ConversionProvider.py",
line 117, in get
    raise Exception("no converter for %s" % cpp_type)
Exception: no converter for PeakT
src/pyOpenMS/CMakeFiles/pyopenms_create_cpp.dir/build.make:58: recipe for
target 'src/pyOpenMS/CMakeFiles/pyopenms_create_cpp' failed
make[3]: *** [src/pyOpenMS/CMakeFiles/pyopenms_create_cpp] Error 1
CMakeFiles/Makefile2:1258: recipe for target
'src/pyOpenMS/CMakeFiles/pyopenms_create_cpp.dir/all' failed
make[2]: *** [src/pyOpenMS/CMakeFiles/pyopenms_create_cpp.dir/all] Error 2
CMakeFiles/Makefile2:1298: recipe for target
'src/pyOpenMS/CMakeFiles/pyopenms.dir/rule' failed
make[1]: *** [src/pyOpenMS/CMakeFiles/pyopenms.dir/rule] Error 2
Makefile:602: recipe for target 'pyopenms' failed
make: *** [pyopenms] Error 2
---


Best regards,
Lars

**Comment by hroest** [comment]
hmm interesting I just ran into the same issue on Windows.

which version of autowrap and Cython are you using? Does it happen with ChromatogramSpectrum? I fear that it may be related to a newer version of Cython as the affected code has been in pyOpenMS since over 2 years and it builds fine here...

I will also look into this and report back

**Comment by hroest** [comment]
@uweschmitt can you also have a look at this as it seems to be some issue which involves the Cython API, autowrap and pyOpenMS

**Comment by malmstroem** [comment]
Hi Hannes,

Thanks for all the help, much appreciated. I have downgraded cython but
still cannot build pyopenms:

-- Building OpenMS 2.0.1
--   - Repository revision c23217e
--   - Repository branch develop
--   - Repository last change date 2016-07-06 10:34:36 -0700
--   [CMake is tracking Git commits and branching. To disable use '-D
GIT_TRACKING=OFF'.]
-- OpenMP: ON
-- Architecture: 64 bit
-- Compiler checks for conversion: OFF
-- Collection of usage statistics and update notifications enabled.
--   If you don't want this information to be transmitted to our update
sever, you can:
--     - Switch the build variable ENABLE_USAGE_STATISTICS to OFF to remove
the functionality at build time.
--     - Set the environment variable OPENMS_DISABLE_USAGE_STATISTICS to
disable the functionality at runtime.
-- Boost version: 1.52.0
-- Adding library OpenSwathAlgo
-- Adding library OpenSwathAlgo - SUCCESS
-- Boost version: 1.52.0
-- Found the following Boost libraries:
--   iostreams
--   date_time
--   math_c99
--   regex
-- Found Boost version 1.52.0
-- Found Qt4: /usr/bin/qmake (found suitable version "4.8.7", minimum
required is "4.6.0")
-- Info: CF_OPENMS_DATA_PATH: /usr/local/openms/OpenMS/share/OpenMS
-- Info: CF_OPENMS_DOC_PATH: /usr/local/openms/OpenMS/doc
-- Adding library OpenMS
-- Adding library OpenMS - SUCCESS
-- Boost version: 1.52.0
-- Adding library SuperHirn
-- Adding library SuperHirn - SUCCESS
-- Python found at /usr/local/openms/tt/bin/python with version 2.7 (if
this is wrong, configure with -DPYTHON_EXECUTABLE:FILEPATH=/path/to/python)
-- Looking for cython - found version 0.23.4
-- Looking for autowrap - found autowrap 0.7.1, version ok
-- Looking for nose testing framework - found
-- Looking for numpy - found
-- Looking for setuptools - found setuptools 24.0.2, version ok
-- Not trying to find Phonon explicitly... If you run into trouble with Qt
Phonon, try to enable it in build system
-- Found Qt4: /usr/bin/qmake (found version "4.8.7")
-- Boost version: 1.52.0
-- Adding library OpenMS_GUI
-- Adding library OpenMS_GUI - SUCCESS
-- No resource file
(/usr/local/openms/OpenMS/src/openms_gui/source/VISUAL/APPLICATIONS/GUITOOLS/IDEvaluatorGUI.rc)
found for IDEvaluatorGUI. No icon will be embedded.
-- No resource file
(/usr/local/openms/OpenMS/src/openms_gui/source/VISUAL/APPLICATIONS/GUITOOLS/INIFileEditor.rc)
found for INIFileEditor. No icon will be embedded.
-- No resource file
(/usr/local/openms/OpenMS/src/openms_gui/source/VISUAL/APPLICATIONS/GUITOOLS/TOPPAS.rc)
found for TOPPAS. No icon will be embedded.
-- No resource file
(/usr/local/openms/OpenMS/src/openms_gui/source/VISUAL/APPLICATIONS/GUITOOLS/TOPPView.rc)
found for TOPPView. No icon will be embedded.
-- Boost version: 1.52.0
-- Found the following Boost libraries:
--   math_c99
-- Found Qt4: /usr/bin/qmake (found version "4.8.7")
-- Boost version: 1.52.0
-- Searching for third party tools...
--   - OMSSA not found
--   - X! Tandem not found
--   - Myrimatch not found
--   - MS-GF+ not found
--   - Fido not found
--   - FidoChooseParameters not found
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)
-- Doxygen not found. Disabling all documentation targets!
-- Note that no documentation will be installed alongside OpenMS.
-- Doxygen or Latex missing. Disabling 'doc_tutorials' target!
--
-- -----------------------------------------------------------------
--
-- You have successfully configured OpenMS.
--
-- For a full list of make targets execute:
-- 'make targets'
--
-- -----------------------------------------------------------------
--
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/openms/OpenMS


I'm attaching the combined log and error of the make pyopenms.


Thanks!
Lars

**Comment by uweschmitt** [comment]
I updated `autowrap` to require `Cython 0.21` and checked this with Python 2.6, 2.7, 3.3, 3.4 and 3.5.

**Comment by uweschmitt** [comment]
@malmstroem : did you forget some attachments ? I do not see what is going wrong...

**Comment by timosachsenberg** [comment]
any news on the problem?

**Comment by malmstroem** [comment]
Hi Timo, Hannes and Uwe,

Sorry for the delay on this. Everything is now working as expected. Thanks!

Best regards,
Lars

**Comment by hroest** [comment]
great!
