### ISSUE TITLE
Possibly Missing Entries in some sources.cmake

### ISSUE THREAD

**Issue by Luxxii** [OpenMS/OpenMS#4601]
Hi everybody, 

I am relatively new to OpenMS. After some trouble with Boost and OpenMS 2.4.0 on Linux i got OpenMS 2.5.0 installed succesfully.

Running commands like `OpenMSInfo` returned succesfully:
```text
OpenMS Version:
==================
Version      : 2.5.0
Build time   : Feb 20 2020, 19:51:01
Git sha1     : f649042
Git branch   : release/2.5.0

Installation information:
==================
Data path    : /usr/bin/../share/OpenMS
Temp path    : /tmp
Userdata path: /home/REMOVED/

Build information:
==================
Source path  : /home/jenkins/ws/openms_release_packaging/fd57e9df/source/src/openms
Binary path  : /home/jenkins/ws/openms_release_packaging/fd57e9df/build/src/openms
Binary arch  : 64 bit

OS Information:
==================
Name: Linux
Version: unknown
Architecture: unknown
```

However, i noticed that i was not able to compile a simple CPP example as given [here](https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/tutorial.html#Spectra). 

```cpp
#include <OpenMS/KERNEL/MSSpectrum.h>

int main() {
    OpenMS::MSSpectrum spectrum;
    OpenMS::Peak1D peak;
    for (float mz = 1500.0; mz >= 500; mz -= 100.0) {
        peak.setMZ(mz);
        spectrum.push_back(peak);
    }
    return 0;
}
```
The Compiler threw:
```text
$:~/git/project$ make
[ 50%] Building CXX object CMakeFiles/main.dir/src/cpp/Main.cpp.o
In file included from /home/REMOVED/git/project/src/cpp/Main.cpp:4:0:
/usr/include/OpenMS/KERNEL/MSSpectrum.h:38:10: fatal error: OpenMS/KERNEL/StandardDeclarations.h: No such file or directory
 #include <OpenMS/KERNEL/StandardDeclarations.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
...
```
And the File `StandardDeclarations.h` is actually missing in `/usr/include/OpenMS/KERNEL`

---

I compared the Sources of f649042  (`OpenMS/src/openms/include/OpenMS/`) with the files present in `/usr/include/OpenMS/` and got the following:

In some `sources.cmake` the following files are not mentioned:

```text
─ ANALYSIS/ID
   └ FIAMSScheduler.h
─ ANALYSIS/QUANTIFICATION
   └ TMTSixteenPlexQuantitationMethod.h
─ APPLICATION
   └ OpenSwathBase.h
─ CONCEPT
   └ Init.h
   └ MacrosTest.h
─ FORMAT
   └ HDF5Connector.h
─ FORMAT/HANDLERS
   └ CachedMzMLHandler.h
─ KERNEL
   └ StandardDeclarations.h

Also Missing (for completeness sake)
─ CHEMISTRY/ISOTOPEDISTRIBUTION
   └ FineIsotopePatternGenerator.h
   └ IsoSpecWrapper.h
```

Also the Folder `ISOTOPEDISTRIBUTION` was missing completely in `/usr/include/OpenMS/CHEMISTRY`

---

I am not sure whether adding the not mentioned Files in `sources.cmake` will let them appear in `/usr/include/OpenMS` so i figured to  report this here. Adding those Files manually will compile the source-code mentioned above but i still get some Linkage Problems (which may be not related to OpenMS)

Greetings!

**Comment by jpfeuffer** [comment]
Hey!
Thanks a lot for reporting and sorry that you had trouble.
Embarrassingly, you were absolutely right. I fixed the includes to be exported right away and will now try to get our tests for external inclusion working correctly (since this seems to have been completely overlooked).
Please let me know about those linking issues that you have, in case something needs to be fixed there.

**Comment by Luxxii** [comment]
Thank You very much for such a quick answer! Unfortunately i still have some Problems building the examples.  (After adding the files manually!)

Here is the `CMakeLists.txt`:
```cmake
# Cmake Minimum Version and Project Name
cmake_minimum_required(VERSION 3.5)
project (projecct)

find_package(Qt5 COMPONENTS Core Network REQUIRED) # Needed for OpenMS
find_package(OpenMP REQUIRED) # Needed for OpenMS
find_package(OpenMS REQUIRED)

# Get the Main.cpp
file(GLOB_RECURSE sources ./src/cpp/*.cpp ./src/cpp/*.h)

add_executable(main ${sources})

target_link_libraries(main OpenMS)
```
With the file `src/cpp/Main.cpp` as mentioned above.

While building i get the following error: 

```text
make[2]: *** No rule to make target '/home/jenkins/ws/openms_release_packaging/fd57e9df/contrib_build/lib/libCbc.a', needed by 'main'.  Stop.
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/main.dir/all' failed
make[1]: *** [CMakeFiles/main.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

Interestingly the path does NOT exist on my computer. It is the same path as from `OpenMSInfo` in the section Build Information. I tried to find those references and found on my machine in the directory `/usr/share/OpenMS/cmake` that the files `OpenMSConfig.cmake` and `OpenMsTargets.cmake` reference those non-existent paths and files. 


--- 

I also tried to build OpenMS 2.5.0 from source. I installed the package then successfully and tried the same again. The same error occurred with changed Paths (as expected):

```text
make[2]: *** No rule to make target '/home/REMOVED/git/AUR_MAINTAINING/openms/src/contrib-build/lib/libCbc.a', needed by 'main'.  Stop.
make[2]: Leaving directory '/home/REMOVED/git/projecct'
make[1]: *** [CMakeFiles/Makefile2:93: CMakeFiles/main.dir/all] Error 2
make[1]: Leaving directory '/home/REMOVED/git/projecct'
make: *** [Makefile:101: all] Error 2
```

The files mentioned in `OpenMSConfig.cmake` and `OpenMsTargets.cmake` also reference non existent files when building manually (like `libCbc.a`). 

For Completeness, here the `OpenMSInfo` after building:
```text
OpenMS Version:
==================
Version      : 2.5.0-HEAD-2020-02-20
Build time   : Mar 23 2020, 14:24:38
Git sha1     : f649042
Git branch   : HEAD

Installation information:
==================
Data path    : /usr/share/OpenMS
Temp path    : /tmp
Userdata path: /home/REMOVED/

Build information:
==================
Source path  : /home/REMOVED/git/AUR_MAINTAINING/openms/src/OpenMS-2.5.0/src/openms
Binary path  : /home/REMOVED/git/AUR_MAINTAINING/openms/src/OpenMS-2.5.0-build/src/openms
Binary arch  : 64 bit

OS Information:
==================
Name: Linux
Version: unknown
Architecture: unknown

```

---

I tried to search for the reason for this error, but i really cannot figure it out whether it is a problem on my end or not. 

I found the references of the mentioned files only here:
https://github.com/OpenMS/OpenMS/blob/d17cc251fd0c4068eb253b03c9fb107897771fdc/cmake/export_macros.cmake#L37

https://github.com/OpenMS/OpenMS/blob/d17cc251fd0c4068eb253b03c9fb107897771fdc/cmake/export_macros.cmake#L60-L65

And the file:  [OpenMsConfig.cmake.in](https://github.com/OpenMS/OpenMS/blob/d17cc251fd0c4068eb253b03c9fb107897771fdc/cmake/OpenMSConfig.cmake.in)


--- 
I hope the problem is clear. Thanks in advance!

**Comment by jpfeuffer** [comment]
Hi! While I understand the first part (when using a packaged version of the library), I don't see why the dependency library paths would be missing in the self-built version of OpenMSConfig.cmake. How are you building OpenMS without libCBC?

I would not recommend to follow-up on the first way but try to get your self-built environment working. I honestly don't think we are doing a good job yet providing a relocatable CMake config file in the packages.

**Comment by Luxxii** [comment]
Rebuilding OpenMS once again solved it for me. Seems like i have messed up on some point. Thanks for the suggestion. Then this Issue can be closed after Merging the changes

**Comment by jpfeuffer** [comment]
Great. By the way, I opened up an issue #4603 to add a functioning OpenMSConfig.cmake to our packages (e.g. debian) but it will be some work. For now, I think building OpenMS yourself (with the same environment; as you did) or writing an own complete CMake file are the only options.
