### ISSUE TITLE
Sirius stalling when called in container

### ISSUE THREAD

**Issue by bernt-matthias** [OpenMS/OpenMS#6068]
When I run SiriusAdapter from inside a container (openms and sirius installed from bioconda), the sirius is stalling (state `Sl` according to `ps aux`): 

```
berntm    446601  0.0  0.0 115392     4 ?        S    Apr25   0:00 SiriusAdapter -ini SiriusAdapter.ctd -in in/SiriusAdapter_1_input_mzML.mzML -out_sirius out_sirius/output.mzTab
berntm    446602  0.0  0.0   5500     4 ?        S    Apr25   0:00 sh /usr/local/share/sirius-csifingerid-4.9.15-2/bin/sirius --processors=1 --input /tmp/20220425_140359_8cad5ecae9f6_15_2.ms --project /tmp/20220425_140359_8cad5ecae9f6_15_1/sirius_out sirius --db=all --ppm-max=10.0 --ppm-max-ms2=10.0 --compound-timeout=100 --tree-timeout=0 --profile=qtof --candidates=5
berntm    446633  0.0  0.0 9943068   84 ?        Sl   Apr25   0:32 /usr/local/share/sirius-csifingerid-4.9.15-2/lib/runtime/bin/java -Xms1G -XX:MaxRAMPercentage=85 -XX:+UseG1GC -XX:+UseStringDeduplication -Djava.library.path=/lib:/bin/x86-64_linux:/usr/local/share/sirius-csifingerid-4.9.15-2/lib/native:/usr/local/share/sirius-csifingerid-4.9.15-2/lib/runtime/lib -classpath /usr/local/share/sirius-csifingerid-4.9.15-2/lib/app/*:/lib/gurobi.jar:/lib/cplex.jar de.unijena.bioinf.ms.frontend.SiriusGUIApplication --processors=1 --input /tmp/20220425_140359_8cad5ecae9f6_15_2.ms --project /tmp/20220425_140359_8cad5ecae9f6_15_1/sirius_out sirius --db=all --ppm-max=10.0 --ppm-max-ms2=10.0 --compound-timeout=100 --tree-timeout=0 --profile=qtof --candidates=5
```

The Sirius command line that is executed by the Adpater (which is printed when I use the debug argument) runs fine if executed directly. 

This makes me guess that there is something wrong in the way Sirius is called .. 

The major problem for debugging is that I could not find a way to access the output of sirius while it is running/stalling or to increase its verbosity.

- @oliveralka suggested to run the OpenMS testst inside of the container https://github.com/OpenMS/OpenMS/pull/6065#issuecomment-1109611877 .. not sure how to do this. 
- see also https://github.com/bioconda/bioconda-recipes/pull/34307#issuecomment-1109573071  https://github.com/bioconda/bioconda-recipes/pull/34482

**Comment by bernt-matthias** [comment]
Maybe related: 

- https://github.com/OpenMS/OpenMS/issues/5268
- https://github.com/OpenMS/OpenMS/issues/3747

**Comment by bernt-matthias** [comment]
Hi @oliveralka after some trickery with SIRIUS' bioconda recipe I have now the stderr of the stalling job

```
INFO: Error when creating PropertyDescriptor for public final void org.apache.commons.configuration2.AbstractConfiguration.setProperty(java.lang.String,java.lang.Object)! Ignoring this property.
Could NOT create Workspace
java.nio.file.AccessDeniedException: /usr/local/bin/?
	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(Unknown Source)
	at java.base/java.nio.file.Files.createDirectory(Unknown Source)
	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Unknown Source)
	at java.base/java.nio.file.Files.createDirectories(Unknown Source)
	at de.unijena.bioinf.ms.frontend.core.ApplicationCore.<clinit>(ApplicationCore.java:121)
	at de.unijena.bioinf.ms.frontend.SiriusCLIApplication.run(SiriusCLIApplication.java:108)
	at de.unijena.bioinf.ms.frontend.SiriusCLIApplication.main(SiriusCLIApplication.java:53)
	at de.unijena.bioinf.ms.frontend.SiriusGUIApplication.main(SiriusGUIApplication.java:56)
```

`/usr/local/bin/` is the directory containing the sirius executable. So apparently SIRIUS is trying to write the workspace in the current working dir... 

According to the docs it should write to `~/.sirius-<X.Y>`, see also [this hidden parameter](https://github.com/boecker-lab/sirius/blob/b2352703a1891cbb9a59d0e2d0d38df4416e1df5/sirius_cli/src/main/java/de/unijena/bioinf/ms/frontend/subtools/CLIRootOptions.java#L103) which we may also use to tell SIRIUS explicitly where to create the workspace.

**Comment by jpfeuffer** [comment]
@bernt-matthias By the way, how did you get out the logs of sirius? I am pretty sure I implemented that once by calling sirius in a different way but it might have been overwritten over time (e.g. when they started to create executables and not using the jar files)

**Comment by bernt-matthias** [comment]
> By the way, how did you get out the logs of sirius?

I modified the patch such that `--loglevel=ALL` is always in the SIRIUS command line https://github.com/bioconda/bioconda-recipes/pull/34482/files (and used the bioconda artifacts for the conda environment that is created in the container)

>  I am pretty sure I implemented that once by calling sirius in a different way but it might have been overwritten over time (e.g. when they started to create executables and not using the jar files)

Also note that the wrapper script changes to the install dir itself (https://github.com/boecker-lab/sirius/blob/bb56e3ded9b7445c233593d92d311860ad531c74/scripts/sirius.sh.templ#L43) in order to set needed paths correctly.

**Comment by mfleisch** [comment]
> Hi @oliveralka after some trickery with SIRIUS' bioconda recipe I have now the stderr of the stalling job
> 
> ```
> INFO: Error when creating PropertyDescriptor for public final void org.apache.commons.configuration2.AbstractConfiguration.setProperty(java.lang.String,java.lang.Object)! Ignoring this property.
> Could NOT create Workspace
> java.nio.file.AccessDeniedException: /usr/local/bin/?
> 	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
> 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
> 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
> 	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(Unknown Source)
> 	at java.base/java.nio.file.Files.createDirectory(Unknown Source)
> 	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Unknown Source)
> 	at java.base/java.nio.file.Files.createDirectories(Unknown Source)
> 	at de.unijena.bioinf.ms.frontend.core.ApplicationCore.<clinit>(ApplicationCore.java:121)
> 	at de.unijena.bioinf.ms.frontend.SiriusCLIApplication.run(SiriusCLIApplication.java:108)
> 	at de.unijena.bioinf.ms.frontend.SiriusCLIApplication.main(SiriusCLIApplication.java:53)
> 	at de.unijena.bioinf.ms.frontend.SiriusGUIApplication.main(SiriusGUIApplication.java:56)
> ```
> 
> `/usr/local/bin/` is the directory containing the sirius executable. So apparently SIRIUS is trying to write the workspace in the current working dir...
> 
> According to the docs it should write to `~/.sirius-<X.Y>`, see also [this hidden parameter](https://github.com/boecker-lab/sirius/blob/b2352703a1891cbb9a59d0e2d0d38df4416e1df5/sirius_cli/src/main/java/de/unijena/bioinf/ms/frontend/subtools/CLIRootOptions.java#L103) which we may also use to tell SIRIUS explicitly where to create the workspace.

@bernt-matthias this problem still exists right?
I am not sure if the hidden parameter for specifying  the workspace of sirius is fully functional.
However it, looks like it will solve the issue so can provide a an update that contains working option.
Since you are doing https://github.com/bioconda/bioconda-recipes/pull/34447 it should be fine to just release a new SIRIUS 
build v4.9.16 and we do not need to backport the changes?
