### ISSUE TITLE
openMS crashing on MacOS Sonoma

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#7999]
### Discussed in https://github.com/OpenMS/OpenMS/discussions/7998

<div type='discussions-op-text'>

<sup>Originally posted by **stpalli** April 25, 2025</sup>
Dear all,

I am trying to install and run openMS on a Mac Sonoma. While the installation is fine, the application TOPPView just crashes as soon as I try to open it. I am attaching a screenshot of the crash error.

<img width="614" alt="Screenshot 2025-04-25 at 9 58 21 AM" src="https://github.com/user-attachments/assets/6c9ee370-5907-4086-85b8-731aa566d890" />
</div>

**Comment by jpfeuffer** [comment]
fixed in https://github.com/OpenMS/OpenMS/issues/7689

**Comment by stpalli** [comment]
I tried the solution provided in https://github.com/OpenMS/OpenMS/issues/7689 but the error still persists.

**Comment by jpfeuffer** [comment]
I don't understand. There wasn't an easy workaround. Did you sign every lib and executable in the package?

It was solved by releasing new installers (i.e. not 3.2.0 but 3.3.0 or 3.4.0dev)
